---
name: "Tag on Version PR Merge"

on:
  pull_request:
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r .version ./src/Packages/Passport/package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Tag
        uses: mathieudutour/github-tag-action@v6
        with:
          tag_prefix: 'v'
          tag_name: ${{ env.VERSION }}
          tag_message: "Version ${{ env.VERSION }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
