---
name: "Tag Release"

on:
  pull_request:
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r .version ./src/Packages/Passport/package.json)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Check TS SDK version exists in index.html
        id: check_ts_sdk_version
        run: |
          version=$(grep -oP '"x-sdk-version":"ts-immutable-sdk-\K[0-9]+\.[0-9]+\.[0-9]+' ./src/Packages/Passport/Runtime/Resources/index.html | head -n 1)

          if [[ -z "$version" ]]; then
            echo "Error: TS SDK version not found in index.html" >&2
            exit 1
          fi

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: "v${{ env.VERSION }}"
          message: "Version ${{ env.VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
