---
name: UI Tests 🧪

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.head.repo.fork == false
    name: Build sample game for AltTester 🛠️
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('sample/Assets/**', 'sample/Packages/**', 'sample/ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneOSX
          projectPath: './sample'
          buildMethod: MacBuilder.BuildForAltTester
          customParameters: -logFile logFile.log -quit -batchmode
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-StandaloneOSX
          path: |
            build/StandaloneOSX
            logFile.log
      