---
name: UI Tests 🧪

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build sample game for AltTester 🛠️
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('sample/Assets/**', 'sample/Packages/**', 'sample/ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: StandaloneOSX
          projectPath: sample
          buildMethod: MacBuilder.BuildForAltTester
          customParameters: -logFile logFile.log -quit -batchmode
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-StandaloneOSX
          path: sample/**
  test:
    name: Run UI tests on AltTester 🧪
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneOSX
      - name: Open application
        working-directory: Builds/MacOS
        run: |
          pwd
          ls -la
          export RUN_IN_BROWSERSTACK="false"
          export ALTSERVER_PORT=13005
          export ALTSERVER_HOST="192.168.11.35"
          chmod -R 755 SampleApp.app
          open SampleApp.app
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r "sample/Tests/requirements.txt"
      