---
name: UI Tests 🧪

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.head.repo.fork == false
    name: Build sample game for AltTester 🛠️
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('sample/Assets/**', 'sample/Packages/**', 'sample/ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_PERSONAL_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PERSONAL_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneOSX
          projectPath: sample
#          buildMethod: MacBuilder.BuildForAltTester
#          customParameters: -logFile logFile.log -quit -batchmode
          cacheUnityInstallationOnMac: true
          allowDirtyBuild: true
      - name: Open application
        working-directory: sample/Builds/MacOS
        run: |
          export RUN_IN_BROWSERSTACK="false"
          export ALTSERVER_PORT=13005
          export ALTSERVER_HOST="192.168.11.35"
          chmod -R 755 SampleApp.app
          open SampleApp.app
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r "sample/Tests/requirements.txt"
      