---
name: UI Tests 🧪

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.targetPlatform }} for AltTester 🛠️
    runs-on: ubuntu-latest-8-cores
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: iOS
            buildMethod: MobileBuilder.BuildForAltTester
            buildPath: build/iOS
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('sample/Assets/**', 'sample/Packages/**', 'sample/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: sample
      - name: List build directory
        run: ls -R ./
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
  test:
    name: Run ${{ matrix.targetPlatform }} UI tests 🧪
    needs: build
    strategy:
      matrix:
        include:
          - targetPlatform: StandaloneOSX
            runs-on: [self-hosted, macOS]
            test_script: test_mac.sh
          - targetPlatform: StandaloneWindows64
            runs-on: [self-hosted, windows]
            test_script: test_windows.ps1
          - targetPlatform: Android
            runs-on: [ self-hosted, macOS ]
            test_script: browserstack-sdk pytest -s ./test/test_android.py
    concurrency:
      group: test-${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/download-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: sample/Tests
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r "sample/Tests/requirements.txt"
      - name: Run UI tests
        env:
          UNITY_APP_PATH: SampleApp.app
          UNITY_APP_NAME: SampleApp
          MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        working-directory: sample/Tests
        run: ${{ matrix.test_script }}
      