---
name: UI Tests 🧪

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build sample game for AltTester ${{ matrix.targetPlatform }} 🛠️
    runs-on: ubuntu-latest-8-cores
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: StandaloneOSX
            buildMethod: MacBuilder.BuildForAltTester
          - targetPlatform: StandaloneWindows64
            buildMethod: WindowsBuilder.BuildForAltTester
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('sample/Assets/**', 'sample/Packages/**', 'sample/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: sample
          buildMethod: ${{ matrix.buildMethod }}
          customParameters: -logFile logFile.log -quit -batchmode
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build
  test:
    name: Run UI tests on AltTester 🧪
    needs: build
    strategy:
      matrix:
        include:
          - targetPlatform: StandaloneOSX
            runs-on: [self-hosted, macOS]
            artifact: Build-StandaloneOSX
            test_script: test_mac.sh
          - targetPlatform: StandaloneWindows64
            runs-on: [self-hosted, windows]
            artifact: Build-StandaloneWindows64
            test_script: test_windows.ps1
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r "sample/Tests/requirements.txt"
      - name: Run UI tests
        env:
          UNITY_APP_PATH: ${{ github.workspace }}/SampleApp.app
          UNITY_APP_NAME: SampleApp
          MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
        working-directory: sample/Tests
        run: |
          chmod -R 755 ${{ github.workspace }}/SampleApp.app
          chmod +x ${{ matrix.test_script }}
          ./${{ matrix.test_script }}
      