---
name: Update zkEVM API Package

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pull files from Git LFS
        run: git lfs pull

      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: Download remote openapi.json
        run: curl -o openapi.json https://imx-openapiv3-mr-sandbox.s3.us-east-2.amazonaws.com/openapi.json

      - name: Ensure local openapi.yaml exists (if not, assume it's blank)
        run: |
          if [ ! -f ./src/Packages/ZkEvmApi/api~/openapi.yaml ]; then
            echo "Creating empty openapi.yaml file..."
            mkdir -p ./src/Packages/ZkEvmApi/api~
            touch ./src/Packages/ZkEvmApi/api~/openapi.yaml
          fi

      - name: Compare openapi.json with openapi.yaml
        id: comparison
        run: |
          if diff openapi.json ./src/Packages/ZkEvmApi/api~/openapi.yaml > /dev/null; then
            echo "::set-output name=difference::false"
          else
            echo "::set-output name=difference::true"
          fi

      - name: Generate API if there are differences
        if: steps.comparison.outputs.difference == 'true'
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.8.0/openapi-generator-cli-7.8.0.jar -O openapi-generator-cli.jar
          java -jar openapi-generator-cli.jar generate -i openapi.json -g csharp \
            --library unityWebRequest -o ./ZkEvmApi \
            --skip-validate-spec \
            --additional-properties=apiName=ImmutableZkEvmApi,packageName=Immutable.Api.ZkEvm

      - name: Copy generated files
        if: steps.comparison.outputs.difference == 'true'
        run: |
          mkdir -p ./src/Packages/ZkEvmApi/api~
          mkdir -p ./src/Packages/ZkEvmApi/Documentation~
          mkdir -p ./src/Packages/ZkEvmApi/Runtime

          # Clear contents while preserving .meta files
          find ./src/Packages/ZkEvmApi/api~ -type f ! -name '*.meta' -exec rm {} +
          find ./src/Packages/ZkEvmApi/Documentation~ -type f ! -name '*.meta' -exec rm {} +
          find ./src/Packages/ZkEvmApi/Runtime -type f ! -name '*.meta' -exec rm {} +

          cp -r ./ZkEvmApi/api/* ./src/Packages/ZkEvmApi/api~/
          cp -r ./ZkEvmApi/docs/* ./src/Packages/ZkEvmApi/Documentation~/
          cp -r ./ZkEvmApi/src/Immutable.Api.ZkEvm/* ./src/Packages/ZkEvmApi/Runtime/

          # Remove .meta files that do not have corresponding files
          for dir in ./src/Packages/ZkEvmApi/Runtime; do
            for meta_file in "$dir"/*.meta; do
              # Check if the corresponding file exists
              base_file="${meta_file%.meta}"
              if [ ! -e "$base_file" ]; then
                echo "Deleting unmatched meta file: $meta_file"
                rm "$meta_file"
              fi
            done
          done

      - name: Clean up
        if: steps.comparison.outputs.difference == 'true'
        run: |
          rm -rf ./ZkEvmApi
          rm openapi-generator-cli.jar
          rm openapi.json

      - name: Open sample app in Unity to generate .meta files
        if: steps.comparison.outputs.difference == 'true'
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: 2021.3.26f1
          projectPath: './sample'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: 'EditMode'

      - name: Create a new branch
        if: steps.comparison.outputs.difference == 'true'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b feat/update-zkevm-api-${{ steps.date.outputs.date }}

      - name: Commit changes
        id: commit_changes
        if: steps.comparison.outputs.difference == 'true'
        run: |
          git add ./src/Packages/ZkEvmApi/
          if [ -n "$(git diff --cached)" ]; then
            git commit -m "feat: update immutable zkEVM API package"
            echo "commit=true" >> $GITHUB_ENV
          else
            echo "No changes to commit."
            echo "commit=false" >> $GITHUB_ENV
          fi

      - name: Push changes
        if: env.commit == 'true'
        run: |
          git push origin feat/update-zkevm-api-${{ steps.date.outputs.date }}

      - name: Create pull request
        if: env.commit == 'true'
        run: |
          gh pr create --title "feat: update immutable zkEVM API package" \
                        --body "Update Immutable zkEVM API package" \
                        --base main \
                        --head feat/update-zkevm-api-${{ steps.date.outputs.date }}